### ISSUE TITLE
random-utest fails with Intel compiler

### ISSUE THREAD

**Issue by nathanweeks** [EddyRivasLab/hmmer#1]
Using the Intel 2016 compiler on a RHEL 6.3 system, the random-utest regression test fails:

```
$ icc --version
icc (ICC) 16.0.0 20150815
Copyright (C) 1985-2015 Intel Corporation.  All rights reserved.

$ ./configure CC=icc
...
$ make check
...
    exercise   29 [         random-utest] ...     FAILED [command failed]
```

In the 2015-08-20 master branch commit (3ecde75c22e07cd821b4addbf2f92a277bc59d5e), both random-utest and normal-utest fail.

**Comment by cryptogenomicon** [comment]
Appears to be specific to icc -O.
I see the issue in esl_random_utest, which makes an assumption that floating point math uses denormalized numbers, but icc disables denormals at all -O levels. Easy to fix; will look into the other failure now.

**Comment by cryptogenomicon** [comment]
Fixed, in a commit to easel.
