### ISSUE TITLE
H3 fails to read old H2 save file

### ISSUE THREAD

**Issue by traviswheeler** [EddyRivasLab/hmmer#116]
ID              h106
TITLE           H3 fails to read old H2 save file
AFFECTS         3.0 and later
FIXED_IN        3.1b2
STATUS          CLOSED
XREF            SRE:2014/0116-bug-h104-h2-savefile
REPORTED_BY     Qing-dong Zeng <zqdong2010@hotmail.com> 
OPENED_DATE     SRE, 16 Jan 2014
CLOSED_DATE     SRE, 16 Jan 2014
DESCRIPTION     
  Zeng provides an example H2 save file that H3 won't read.
  H3 claims bad format. The save file appears to be from 
  a 1998 version of SMART.

  Two problems identified. One is that the file has a DESC
  line but no description. Fixed p7_hmmfile.c::read_asc20hmm()
  to allow this.

  Second is that hmmemit (only?) complains "whoops, HMM is bad!",
  because hmmemit does a p7_hmm_Validate() on the model, and it's
  slightly nonnormalized. Fixed by adding a p7_hmm_Renormalize() call
  to the end of read_asc20hmm().

**Comment by chasemc** [comment]
I'm encountering what seems like the same issue :

hmmer version:      bioconda/linux-64::hmmer-3.3.2-h87f3376_2
```
$ hmmemit -h
# hmmemit :: sample sequence(s) from a profile HMM
# HMMER 3.3.2 (Nov 2020); http://hmmer.org/
# Copyright (C) 2020 Howard Hughes Medical Institute
```

Note: The HMM in the url can be downloaded but not redistributed
```
$ curl -s https://magarveylab.ca/Skinnider_etal/models/hmm/thiotemplated/cMT.hmm > cMT.hmm
$ hmmemit cMT.hmm
whoops, HMM is bad!
$ hmmconvert cMT.hmm > temp.hmm
$ hmmemit temp.hmm
whoops, HMM is bad!
```
