### ISSUE TITLE
hmmc crash because 32-bit int used for size of data object

### ISSUE THREAD

**Issue by npcarter** [EddyRivasLab/hmmer#123]
In some of my testing, I've gotten crashes in hmmc2 (the sample front-end to hmmpgmd) because my biggest test cases are returning more data than n, the variable used to hold the size of the data object being returned, can represent.  I've changed the type of n from int to uint64_t in my local copy.  Is this something we want to check back in to the master?

**Comment by cryptogenomicon** [comment]
Which data object do you mean?

**Comment by npcarter** [comment]
Huh, that would have been useful information to include in the bug report, wouldn’t it?  

The error I’m seeing is from the malloc on line 471 (or so) that allocates memory for the object named “data” whose size has just been sent over the sockets connection.

-Nick

**Comment by cryptogenomicon** [comment]
Yes, <n> should be uint64_t, matching the type of sstatus.msg_size in our HMMD_SEARCH_STATUS struct. Do check that change into h3-develop and the h4 master.

Longer term, we also need to have a hard look at this output; if the daemon is sending >2GB of output back to its client, that's insanity. This is what the work on alignment output compression is designed to address, for example.

**Comment by npcarter** [comment]
Done.

-Nick

**Comment by cryptogenomicon** [comment]
Looks like this did indeed get fixed, so I'm closing the issue.
