### ISSUE TITLE
HMMER Web Service Range Parameter Total Row Count

### ISSUE THREAD

**Issue by ayedo** [EddyRivasLab/hmmer#130]
Hi,

first of all: thanks for your great work on hmmer, and its web server.

I'm following the [https://hmmer-web-docs.readthedocs.io/en/latest/api.html#results.](documentation) to collect results of a hmmsearch remote API call. I was wondering, if there is a way to get the total row count of the result when used with the `range` parameter?

**Comment by cryptogenomicon** [comment]
Apologies, you need to contact the folks at EBI about this. They're the maintainers of the EBI web servers.
