### ISSUE TITLE
a change at position 5 of my query sequence causes position 1 to be designated a deletion, but only in v3, not v2

### ISSUE THREAD

**Issue by hervold** [EddyRivasLab/hmmer#137]
This is the consensus sequence, generated by calling hmmemit -c on my model (which I've attached) and making one edit -- a substitution at position 1:

EVQLVESGAELVKPGESLKLSCAASGFTFSSYALSWVRQAPGKGLEWVGLISSSGSTEYADSLKGRVTISRDTSKNTLYLKLSSLRAEDTAVYYCAREYFDVWGQGTLVTVSS

hmmsearch (and hmmalign) correctly match this sequence with my model.

This is the same sequence with a single substitution at position 5:

EVQLLESGAELVKPGESLKLSCAASGFTFSSYALSWVRQAPGKGLEWVGLISSSGSTEYADSLKGRVTISRDTSKNTLYLKLSSLRAEDTAVYYCAREYFDVWGQGTLVTVSS

This second query causes hmmsearch (and hmmalign) to identify the first position as a "deletion," ie, the alignment begins at position 2, but seems identical otherwise.  This behavior is present in a couple versions of hmmer 3.x, but not in v2, so my best guess is that it has something to do w/ the heuristics.

Thanks for any help you can provide!

[Vh-linker-Vk.hmm.gz](https://github.com/EddyRivasLab/hmmer/files/1940399/Vh-linker-Vk.hmm.gz)

**Comment by cryptogenomicon** [comment]
It's identifying it as a local alignment, not as a deletion. This isn't a bug; exact details of any point estimate of the alignment are sensitive to details of the probability parameters, and thus of the alignment you built your model from.
