### ISSUE TITLE
jackhmmer --fast segfaults

### ISSUE THREAD

**Issue by abretaud** [EddyRivasLab/hmmer#140]
Hi,
While updating the Hmmer Galaxy tool to the brand new 3.2 version [in this pull request](https://github.com/galaxyproject/tools-iuc/pull/1930) I found a problem with jackhmmer crashing with a segfault.
The command line to reproduce the segfault:
```
jackhmmer -N 5  --tblout 'output1'  --domtblout 'output2'  --notextw     -E 10.0 --domE 10.0          --F1 0.02 --F2 0.001 --F3 1e-05    --fast  --symfrac 0.5 --fragthresh 0.5   --wpb          --EmL 200 --EmN 200 --EvL 200 --EvN 200 --EfL 100 --EfN 200 --Eft 0.04        --cpu 2   --seed 4   'input1' 'input2' > 'output3'
```
and here's the test data: [input1](https://github.com/galaxyproject/tools-iuc/blob/master/tools/hmmer3/test-data/uniprot_matches.fasta) and [input2](https://github.com/galaxyproject/tools-iuc/blob/master/tools/hmmer3/test-data/globins45.fa)

It uses the conda package of hmmer I updated this morning, the commands used for compiling it are in this [conda recipe](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/hmmer/build.sh).

Do you see what could be the problem?

**Comment by cryptogenomicon** [comment]
Thanks, I see it. It's coming from the `--fast` option, which I confess I don't test or use in jackhmmer. I'm looking into it now. Meanwhile, workaround is to not use `--fast`.

**Comment by cryptogenomicon** [comment]
I just checked a fix in on our develop branch. The fix removes the --fast option from jackhmmer, also the --symfrac option.  These options shouldn't have been there in the first place. I'll release a 3.2.1 with this and some other fixes soon. In the meantime, an entirely sufficient fix is not to use --fast or --symfrac; just remove them from your testing. Thanks again!

**Comment by abretaud** [comment]
Thanks for looking into it! I've removed these options from the galaxy wrappers
