### ISSUE TITLE
Compilation fails on ppc64le

### ISSUE THREAD

**Issue by cryptogenomicon** [EddyRivasLab/hmmer#142]
HMMER3 compilation fails ungracefully on PowerPC ppc64le (little-endian) machines.

PowerPC Altivec/VMX instructions are used on both big-endian or little-endian platforms, but our code currently just refers to a "VMX implementation", despite the fact that our vector implementations are sensitive to byte order. To make things more confusing, the HMMER3 and HMMER4 VMX implementations are currently written for _different_  byte orders.

The (older) HMMER3 Altivec/VMX implementation assumes _*big-endian*_ architecture, e.g. Power 7; Power8 and Power9 machines can be booted into bigendian mode. The (newer) HMMER4 Altivec/VMX implementation assumes  _*little-endian*_ architecture. Easel's test for VMX support does not distinguish, and some of Easel's `esl_vmx` utilities assume _*little-endian*_; the only reason this is working for us is that H3 does not use these utilities, calling VMX instructions directly.

It appears that bigendian PowerPC (e.g. 32-bit powerpc, 64-bit ppc) are on their way out, and littleendian PowerPC (e.g. ppc64le) is likely to take over. IBM announced in ~2015-16 that they are moving toward only supporting LE on Power 8/9 Linux platforms, and they seem to be pushing their partners (Ubuntu, SUSE, Red Hat) hard to switch to LE exclusively. Ubuntu and SUSE now appear to support only LE; Red Hat, Debian, Fedora, openSUSE appear to support LE and BE; Fedora has announced that they are transitioning toward LE and deemphasizing BE.

We will continue supporting H3 on BE (32bit powerpc and ppc64). We have no plans to introduce a ppc64le port of H3, because we'd rather focus on HMMER4 development.

Conversely, HMMER4 will support ppc64le when it is released, and we have no current plans to introduce a ppc64 or powerpc (32bit) port of H4 -- but we could, if there were demand for it.

The HMMER3 configure script does not currently distinguish between BE and LE when it activates a VMX implementation, and as a result, compilation fails on an LE machine, hence I'm opening this issue as a bug.

**Comment by cryptogenomicon** [comment]
Now this is just an issue for H4.

**Comment by matteodelucchi** [comment]
I would need HMMER on a ppc64le system. I tried cloning the H4 development branch but the regular "./configure make" procedure doesn't work for installing. Is there a way to get a ppc64le system version? If so, how?

**Comment by cryptogenomicon** [comment]
I'm sorry, HMMER4 is in development, and I'm not able to answer questions about the H4 development branch until it is much closer to release.

**Comment by npcarter** [comment]
Closing this issue.  The filters required to make H4 build on LE POWER machines were added a while back, but the Github issue remained open.
