### ISSUE TITLE
3.2.1 binaries are not available

### ISSUE THREAD

**Issue by hsiaoyi0504** [EddyRivasLab/hmmer#143]
On website

http://eddylab.org/software/hmmer3/

**Comment by cryptogenomicon** [comment]
Please see the User's Guide, which discusses why.

**Comment by hsiaoyi0504** [comment]
Thanks, I have read through some part of it, but I can't find it. Do you mind to provide me a keyword or which section I can find it ? Thanks again.

**Comment by cryptogenomicon** [comment]
Apologies, I had an explanation in there at one point, but it looks like it didn't survive editing.

See installation documentation for how to install precompiled binaries using standard software packaging distributions, such as Homebrew, MacPorts, and so on. I no longer distribute precompiled binaries myself, and instead I'm going to rely on the downstream package providers. I expect that they will pick up HMMER 3.2.1 in due course.

**Comment by hsiaoyi0504** [comment]
Thanks for the information. Alternatively, do you think it would be good to use CI like Travis to build the binaries and host them on github ?
- https://docs.travis-ci.com/user/deployment/releases/
- https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
- https://www.victorhurdugaci.com/github-releases-travis

I can try to do this and make a pull request in my free time.

**Comment by cryptogenomicon** [comment]
Thanks, but given that HMMER is already made available as executables by many packaging systems, I think it would require unnecessary added complexity for me to maintain that. Trying to keep things simple.

**Comment by hsiaoyi0504** [comment]
OK, understand.
For those who seeking the pre-compiled packages. Give a try downloading pre-compiled binary for bioconda conda package. It should be straightforward to use them https://anaconda.org/bioconda/hmmer/files.

**Comment by cryptogenomicon** [comment]
Yes, thanks - indeed bioconda is already listed in the installation documentation I pointed you toward in the user guide.

**Comment by hsiaoyi0504** [comment]
Yep, you are right. However, it seems to me that some people don't know that it's easy to get pre-compiled binaries without using specific package manager (conda here) like me.
