### ISSUE TITLE
Alignment input parse error

### ISSUE THREAD

**Issue by csijcs** [EddyRivasLab/hmmer#147]
I'm having trouble running hmmer on a fasta of amino acid sequences. I am running:

`hmmbuild -f isoformSwitchAnalyzeR_isoform_AA.hmm isoformSwitchAnalyzeR_isoform_AA.fasta`

And I get the following error:

```
Alignment input parse error:
   sequence ENST00000000412.7 has alen 277; expected 180
   while reading aligned FASTA file isoformSwitchAnalyzeR_isoform_AA.fasta
   at or near line 10
```
Can you please tell me what I'm doing wrong?  I have run small files on the website before, but this file has over 50,000 sequences, so too many to do on the site.

Thanks,
Joe

**Comment by csijcs** [comment]
Thanks for your reply.  I've consulted the manual and it's just not very straightforward. My favorite section is on how to not have to read the manual.  Maybe you can help me.  I have this fasta output from a program that I have used on the the hmmer site before without issue.  I'm not clear on how exactly to use the standalone program to get the pfam analysis from this fasta.  It thought I needed to build the hmm profile first, but apparently I can't do that with this unaligned fasta.  So do I need to align the fasta? To what? Using tools from the hmmer program? Do I need to convert to Stockholm format? What is the process that is used by the program online? It's not clear to me in the manual because it seems to start with an aligned Stockholm file and I don't know how to get that. I have no experience with this and am trying to figure out how to use it. Any help would be much appreciated.

**Comment by cryptogenomicon** [comment]
You haven't explained what you're trying to do - and even if you did it's not really practical for me to give individual help on how to do your analysis, unfortunately, though I wish there were time for that. Better to chat with someone around you who's done this sort of thing before.

**Comment by shiting878** [comment]
Did you solve your problem? I also happened the same trouble, could you give me a favor, plz?

**Comment by cryptogenomicon** [comment]
hmmbuild requires an alignment file:

```
   hmmbuild <output_hmmfile> <input_alignmentfile>
```

If the alignment file is in "FASTA" format it has to be _aligned_ FASTA format (with gaps included; each sequence the same length).
