### ISSUE TITLE
Compilation of v3.2.1 fails due to lib easel not linked

### ISSUE THREAD

**Issue by fbreitwieser** [EddyRivasLab/hmmer#148]
Thanks for providing this great tools.

I had the following errors when trying to compile hmmer v3.2.1 with GNU Make 3.82 /
gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC):

```
...
     SUBDIR miniapps
     GEN esl-afetch
     GEN esl-alimanip
/tmp/ccfuqGxq.o: In function `main':
esl-alimanip.c:(.text.startup+0x23c0): undefined reference to `esl_arr2_Destroy'
esl-alimanip.c:(.text.startup+0x23db): undefined reference to `esl_arr2_Destroy'
esl-alimanip.c:(.text.startup+0x2401): undefined reference to `esl_free'
esl-alimanip.c:(.text.startup+0x240e): undefined reference to `esl_free'
collect2: error: ld returned 1 exit status
make[2]: *** [esl-alimanip] Error 1
make[1]: *** [all] Error 2
make: *** [all] Error 2
```

I.e. gcc command cannot find lib easel. This is one of the gcc commands (working directory: `easel/miniapps`) that fails:

```gcc -std=gnu99 -O2 -msse2 -pthread  -DHAVE_CONFIG_H -L/ccb/sw/lib -L.. -I. -I.. -I. -I./.. -o esl-alimask esl-alimask.c -leasel  -lm```

I could make it compile by replacing `-leasel` with the path to the library (`../libeasel.a`). I'm not sure why it would not work before, because the original command line does include the directory of the library (`-L..`). It seems to me it's a GCC bug, but wanted to report it. FYI, after fixing minimap the same ld errors appeared in other parts of the HMMER source code, which required the same 'fix'.

**Comment by cryptogenomicon** [comment]
Interesting, thanks. What OS and hardware? I'd like to try to reproduce it here, if we have a similar machine available.
