### ISSUE TITLE
The following error occurred during installation

### ISSUE THREAD

**Issue by lzyAzeii** [EddyRivasLab/hmmer#150]
liuzy@lifeng-PowerEdge-R730:~/tool/hmmer-3.2.1$ make install
/usr/bin/install -c -d /usr/local/bin
/usr/bin/install -c -d /usr/local/share/man/man1
make -C src install
make[1]: Entering directory `/home/liuzy/tool/hmmer-3.2.1/src'
for file in alimask hmmalign hmmbuild hmmconvert hmmemit hmmfetch hmmlogo hmmpgmd hmmpress hmmscan hmmsearch hmmsim hmmstat jackhmmer phmmer nhmmer nhmmscan makehmmerdb; do \
	   /usr/bin/install -c -m 0755 $file /usr/local/bin/ ;\
	done
/usr/bin/install: cannot create regular file ‘/usr/local/bin/alimask’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmalign’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmbuild’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmconvert’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmemit’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmfetch’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmlogo’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmpgmd’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmpress’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmscan’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmsearch’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmsim’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/hmmstat’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/jackhmmer’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/phmmer’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/nhmmer’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/nhmmscan’: Permission denied
/usr/bin/install: cannot create regular file ‘/usr/local/bin/makehmmerdb’: Permission denied
make[1]: *** [install] Error 1
make[1]: Leaving directory `/home/liuzy/tool/hmmer-3.2.1/src'
make: *** [install] Error 2

**Comment by lzyAzeii** [comment]
Wish someone could give me some advice,thanks

**Comment by cryptogenomicon** [comment]
This is a general (and common) unix question, not specific to HMMER. You don't have write permission in /usr/local/bin. Either use `sudo make install` or configure to install in a directory that you can write to.
