### ISSUE TITLE
Reading target sequences from stdin - hmmsearch

### ISSUE THREAD

**Issue by iferres** [EddyRivasLab/hmmer#151]
Hi, I'm using HMMER 3.1b2. I was trying to pipe the target sequences (many) from stdout of other process to the stdin of hmmsearch to avoid writing/reading operations on disk, until I read in the HMMER manual:

> Either the query <hmmfile> or the target <seqdb> may be '-' (a dash character), in which case the query profile or target database input will be read from a <stdin> pipe instead of from a file. Only one input source can come through <stdin>, not both. An exception is that if the <hmmfile> contains more than one profile query, then <seqdb> cannot come from <stdin>, because we can't rewind the streaming target database to search it with another profile. 

Since I'm a biologist I'm not fully able to understand this message, but I suppose that is an algorithm restriction. I was wondering if this will be possible on future HMMER versions. 

Thanks, 
Ignacio

**Comment by cryptogenomicon** [comment]
What you say you're doing will work fine - you can stream stdout from one process into HMMER programs, by giving `-` as the input file "name".

You can't read two different files from one stream, so only one input file can be `-`.

If you're streaming an entire target database through the pipe, you can only search it once (i.e. your query can only be one profile or one sequence). This isn't so much an algorithm restriction, more a common sense thing: if you're streaming the data past the query, and now you want to search the same database with a different query, how do you get the database back, if it already streamed by? We'd have to cache the whole stream in memory to make this work, and many target sequence databases are impractically large for this.  If you need to do multiple searches of the same stream, just save it to a file, search the file.

**Comment by iferres** [comment]
I see. Thanks for fast response!
Bests
