### ISSUE TITLE
Mac OS 10.14.4 -configure: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by CK-X** [EddyRivasLab/hmmer#155]
bug:
[bug-(configure- error- C compiler cannot create executables).docx](https://github.com/EddyRivasLab/hmmer/files/3106084/bug-.configure-.error-.C.compiler.cannot.create.executables.docx)
[config.log](https://github.com/EddyRivasLab/hmmer/files/3106085/config.log)

Mac OS 10.14.4 -configure: error: C compiler cannot create executables

**Comment by cryptogenomicon** [comment]
It appears that you don't have a C compiler.

Install a C compiler (for example, install Apple's Xcode), or use a prepackaged binary distribution of HMMER (for example, from homebrew).

**Comment by CK-X** [comment]
The problem has been solved, thank you very much for your help.
