### ISSUE TITLE
Report an error-Alignment input parse error:

### ISSUE THREAD

**Issue by CK-X** [EddyRivasLab/hmmer#156]
I am using the protein sequence ".fasta"files of two species (oryza sativa HAK and Arabicdopsis thaliana KUP protein sequence ".fasta file") to create a new ".hmm" file with the following error：
ocalhost:hmmer ligeng$ ./hmmbuild KUP.hmm AtKUP-OSHAK
# hmmbuild :: profile HMM construction from multiple sequence alignments
# HMMER 3.2.1 (June 2018); http://hmmer.org/
# Copyright (C) 2018 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# input alignment file:             AtKUP-OSHAK
# output HMM file:                  KUP.hmm
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# idx name                  nseq  alen  mlen eff_nseq re/pos description
#---- -------------------- ----- ----- ----- -------- ------ -----------
Alignment input parse error:
   sequence sp|Q9FE38|POT3_ARATH has alen 775; expected 785
   while reading aligned FASTA file AtKUP-OSHAK
   at or near line 30
------------------------------------------------------------------------------
How to solve this problem

**Comment by cryptogenomicon** [comment]
Please refer to the user guide. `hmmbuild` takes an alignment file as input, not an unaligned FASTA file. The error message indicates that it's trying to read your input as an aligned FASTA file and failing.
