### ISSUE TITLE
fail to install hmmers

### ISSUE THREAD

**Issue by limin321** [EddyRivasLab/hmmer#167]
I tried both command line to install hmmer, every looks okay. Just command not found. Here is the information
(base) campus-040-014:~ dklabuser$ conda install -c biocore hmmer
/Users/dklabuser/miniconda2/lib/python2.7/site-packages/cryptography/hazmat/primitives/constant_time.py:26: CryptographyDeprecationWarning: Support for your Python version is deprecated. The next version of cryptography will remove support. Please upgrade to a 2.7.x release that supports hmac.compare_digest as soon as possible.
  utils.DeprecatedIn23,
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/dklabuser/miniconda2

  added / updated specs:
    - hmmer

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.7.8                |           py27_0         3.0 MB  conda-forge
    conda-package-handling-1.3.11|           py27_0         256 KB  conda-forge
    hmmer-3.1b2                |                0         5.7 MB  biocore
    libarchive-3.3.3           |    heb9f7fe_1003         1.5 MB  conda-forge
    lz4-c-1.8.1.2              |                0         119 KB  conda-forge
    lzo-2.10                   |    h1de35cc_1000         176 KB  conda-forge
    python-libarchive-c-2.8    |        py27_1004          20 KB  conda-forge
    tqdm-4.32.2                |             py_0          41 KB  conda-forge
    zstd-1.3.3                 |                1         1.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        11.9 MB

The following NEW packages will be INSTALLED:

  conda-package-han~ conda-forge/osx-64::conda-package-handling-1.3.11-py27_0
  libarchive         conda-forge/osx-64::libarchive-3.3.3-heb9f7fe_1003
  lz4-c              conda-forge/osx-64::lz4-c-1.8.1.2-0
  lzo                conda-forge/osx-64::lzo-2.10-h1de35cc_1000
  python-libarchive~ conda-forge/osx-64::python-libarchive-c-2.8-py27_1004
  tqdm               conda-forge/noarch::tqdm-4.32.2-py_0
  zstd               conda-forge/osx-64::zstd-1.3.3-1

The following packages will be UPDATED:

  conda                                       4.6.14-py27_0 --> 4.7.8-py27_0

The following packages will be SUPERSEDED by a higher-priority channel:

  hmmer                    bioconda::hmmer-3.2.1-h0a44026_1 --> biocore::hmmer-3.1b2-0

Proceed ([y]/n)? y

Downloading and Extracting Packages
lzo-2.10             | 176 KB    | ###################################################################################################################### | 100% 
libarchive-3.3.3     | 1.5 MB    | ###################################################################################################################### | 100% 
tqdm-4.32.2          | 41 KB     | ###################################################################################################################### | 100% 
conda-4.7.8          | 3.0 MB    | ###################################################################################################################### | 100% 
zstd-1.3.3           | 1.1 MB    | ###################################################################################################################### | 100% 
lz4-c-1.8.1.2        | 119 KB    | ###################################################################################################################### | 100% 
conda-package-handli | 256 KB    | ###################################################################################################################### | 100% 
hmmer-3.1b2          | 5.7 MB    | ###################################################################################################################### | 100% 
python-libarchive-c- | 20 KB     | ###################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) campus-040-014:~ dklabuser$ hmmer
-bash: hmmer: command not found
(base) campus-040-014:~ dklabuser$ hmmer -h
-bash: hmmer: command not found
(base) campus-040-014:~ dklabuser$ which hmmer
(base) campus-040-014:~ dklabuser$ hmmer --version
-bash: hmmer: command not found

Then I download hmmer from website again and run the following command:
(base) campus-040-014:~ dklabuser$ cd Scripts/hmmer-3.2.1/
(base) campus-040-014:hmmer-3.2.1 dklabuser$ ./configure --prefix .
configure: error: expected an absolute directory name for --prefix: .
(base) campus-040-014:hmmer-3.2.1 dklabuser$ ./configure --prefix /hmmer-3.2.1/
configure: Configuring HMMER3 for your system.
(base) campus-040-014:hmmer-3.2.1 dklabuser$ make
     SUBDIR easel
     CC easel.o
     CC esl_alloc.o
     CC esl_alphabet.o
     CC esl_arr2.o
(base) campus-040-014:hmmer-3.2.1 dklabuser$ make check
     SUBDIR easel
     GEN easel_utest
(base) campus-040-014:hmmer-3.2.1 dklabuser$ make install
/usr/bin/install -c -d /hmmer-3.2.1/bin
install: mkdir /hmmer-3.2.1: Permission denied
make: *** [install] Error 71
(base) campus-040-014:hmmer-3.2.1 dklabuser$ hmmer
-bash: hmmer: command not found
(base) campus-040-014:hmmer-3.2.1 dklabuser$ nano .bash_profile
(base) campus-040-014:hmmer-3.2.1 dklabuser$ hmmer3
-bash: hmmer3: command not found

Both those two commands installation looks okay. Why  I just couldn't make the program running after installation.

Can anyone have some ideas. You ARE GREATLLY APPRECIATED.

**Comment by cryptogenomicon** [comment]
See the [User Guide](http://eddylab.org/software/hmmer/Userguide.pdf).
