### ISSUE TITLE
makehmmerdb fails with extremely large number of input sequences

### ISSUE THREAD

**Issue by manu-script** [EddyRivasLab/hmmer#168]
makehmmerdb works very well with medium to large inputs. But it fails with a realloc error for extremely large inputs. For example, if I have to make a nhmmerdb of the whole of NCBI nucleotide fasta sequences (or even complete eukaryotic or prokaryotic records) it returns the following error: 

Fatal exception (source file esl_sq.c, line 227):                                                                                                                               realloc for size 18815616 failed

I have tried tweaking the parameters of bin_length and block_size but couldn't get it working.
I am using Hmmer 3.2.1 on a ubuntu 18.04.3 server with 1TB memory. 

Please suggest me, if there are any workarounds.

**Comment by cryptogenomicon** [comment]
Thanks, we're looking into this. There does seem to be a problem in how `makehmmerdb` allocates memory.

**Comment by npcarter** [comment]
To follow up on this, it's taken a while to understand this bug, but I think I have a plan to fix it in the near future.  However, in tracking down the bug, we discovered that processing a database with makehmmerdb can have a significant impact on the number of hits nhmmer finds.   On the test case we ran here, nhmmer found 25% fewer hits when searching a database that had been processed with makehmmerdb than it did when searching the FASTA version of the database. In addition, at least some of the hits that were missed were strong hits, not ones that were near the e-value threshold.  We've flagged this as a separate bug, but don't have an ETA on when it'll be fixed.  Unless you really need the speed advantages of makehmmerdb, my recommendation would be to stick with the original format of your databases until we can fix this correctness bug.

**Comment by cryptogenomicon** [comment]
The new HMMER 3.3 release (18 Nov) contains improvements that we think have addressed this issue.

**Comment by RivasLab** [comment]
Two follow ups on makehmmerdb. 

- This error may be useful for further development. The new error we find when trying to run makehmmerdb on the 600GB vertebrate database after 9.5h running is: 
                                           buildAndWriteFMIndex: Error writing T in FM index.

- This error may be useful for us. In other database, we find an easel input file error:
           Fatal exception (source file esl_buffer.c, line 1608):
           failed to slurp /n/eddyfs01/data/genomes/100_verts
  
   Is this a formatting error in the input file? Does this error give us an indication of what it may be? Thanks.

**Comment by cryptogenomicon** [comment]
On the second point... can you give us a reproducible test case (ideally a small one)?

And how large is the 100_verts file? The "slurping" in esl_buffer is only supposed to occur when the entire file is small enough to slurp easily into memory: currently set to 4MB. On a larger file, it should not be executing this code. But I assume 100_verts is a large file?

**Comment by npcarter** [comment]
Another question: what machine are you running these on?  With a database
that large, I'm wondering if you're hitting out-of-memory problems.

-Nick

**Comment by RivasLab** [comment]
Update. The previous slurping error we reported was not real. The DB file was not really a file but a directory name.
Sorry about that.

We have more reports of FM index failures. 

For file /n/eddyfs01/data/genomes/invertebrates/invertebrate_genomes_db.fasta
makehmmerdb failed after 10.5 h: 

buildAndWriteFMIndex: Error writing BWT in FM index.

For file /n/eddyfs01/data/genomes/100_verts/100_verts.fa
makehmmerdb failed after 7.5h:

buildAndWriteFMIndex: Error writing SA in FM index.

thanks
elena

I

**Comment by traviswheeler** [comment]
I think Nick's question still holds: what machine is it on, and what's the disk space situation on that machine. That space question applies to both the drive you've named in the command, and also wherever /tmp is mounted.  The output of 'df -h' would probably help here. 
I ask about /tmp, because I believe that error is happening while writing a temporary copy of the suffix array, into a file created by a call to esl_tmpfile().  By default, that will create a file in /tmp. If you're running this on a clustered system, it's possible that you have plenty of space on the networked disk, but that /tmp is mounted to a much smaller local disk ... so easy to overwhelm. If that setup describes your system (lots of space in $HOME, not much in /tmp), you might try setting the $TMPDIR environment variable to point to a directory inside $HOME - esl_tmpfile() respects that env variable when creating a temp file.  (this is not captured in makehmmerdb's documentation, and probably should be)

**Comment by npcarter** [comment]
Travis' comment twigged something in my memory.  We've had trouble in the
past wsith makehmmerdb overflowing the /tmp directories on Odyssey
machines, possibly during William's work.  Given the size of your database
file and the errors you're seeing, I think the idea of setting $TMPDIR so
that your temporary files go into one of our large filesystems (/n/eddyfs03
or /n/holylfs03) may well solve your problem.

-Nick
