### ISSUE TITLE
--qfasta affects the number of hits NHMMER finds

### ISSUE THREAD

**Issue by npcarter** [EddyRivasLab/hmmer#171]
When searching a single FASTA-format sequence against a database, NHMMER sometimes finds different numbers of hits when it infers the format of the sequence than when --qfasta is passed to specify the sequence format.  The issue appears to be that NHMMER treats a single FASTA sequence as a one-sequence alignment rather than a single sequence.

**Comment by traviswheeler** [comment]
This was resolved by PR https://github.com/EddyRivasLab/hmmer/pull/194
