### ISSUE TITLE
restoring points for hmmer analyses

### ISSUE THREAD

**Issue by cmuenchow** [EddyRivasLab/hmmer#179]
Hi,
I'm using phmmer for some analyses and my analyses aborted after many weeks due to a short power outrage. Does hmmer have any restore points to restart the calculation from that point on? I didn't find anything about it in the documentation but I am still hopeful to not loose weeks of calculation time. Any suggestions?
Thanks

**Comment by cryptogenomicon** [comment]
No, it doesn't, sorry.
