### ISSUE TITLE
HMMSCAN error in batch submission

### ISSUE THREAD

**Issue by Geize** [EddyRivasLab/hmmer#181]
I have several genomes fasta files for screening based on HMM. I wrote this very simple script. It seems that works - the output files are right. However, I also got this message

"Incorrect number of command line arguments. Usage: hmmscan [-options] <hmmdb> <seqfile>

where most common options are: -h : show brief help on version and usage

To see more help on available options, do /Users/alexjones/miniconda3/bin/hmmscan -h"

Someone knows why I get this message? The script is wrong?

I appreciate any tips. 
Thanks

```
for file in ./*.fasta;
do
  hmmscan --domtblout ${file}.out.dm Target_HMM.txt ${file} > ${file}.out;
done
```

**Comment by cryptogenomicon** [comment]
Script looks fine. One thing you can do to try to find what's wrong is to echo the commands and see if they look right:

```
    for file in ./*.fasta;
    do
        echo "hmmscan --domtblout ${file}.out.dm Target_HMM.txt ${file} > ${file}.out";
    done
```

**Comment by Geize** [comment]
Hi, 

Thanks for your help. 

However, if I add echo commands... I still get the same message and only the file.out. I am using Mac.

**Comment by cryptogenomicon** [comment]
You can't get the same message if you're echo'ing the command line instead of running hmmscan, because that error message comes from trying to run hmmscan.

This doesn't sound like a HMMER problem, but rather a problem with how you're using bash. Suggest asking someone around you with experience in using bash.
