### ISSUE TITLE
problem compiling

### ISSUE THREAD

**Issue by lfaino** [EddyRivasLab/hmmer#182]
Dear Develpper,
i`m trying to add hmmer to a docker container but i get this error:

`     SUBDIR miniapps
     GEN esl-alimanip
In file included from /usr/local/include/assert.h:5:0,
                 from esl-alimanip.c:8:
/usr/local/include/except.h:5:10: fatal error: config.h: No such file or directory
 #include <config.h>  /* For HAVE_PTHREAD */
          ^~~~~~~~~~
compilation terminated.
Makefile:100: recipe for target 'esl-alimanip' failed
make[1]: *** [esl-alimanip] Error 1
Makefile:526: recipe for target 'all' failed
make: *** [all] Error 2
`

however, if i us the make command out of the container, i do not get any error.

do i miss a specific library? any idea?

thanks
Luigi

**Comment by cryptogenomicon** [comment]
Looks like the compile is failing in your system header files, not in HMMER, so my guess is that this is some sort of problem with how you have the container's environment installed. See if you can compile other software, especially something that's trying to `#include <assert.h>`... even a small test program might be revealing.
