### ISSUE TITLE
Package missing in current linux-64 channels (conda installation)

### ISSUE THREAD

**Issue by ciemanek** [EddyRivasLab/hmmer#183]
HI!

While trying to install HMMER via conda `environment.yml`file, I come across a following error:

```
Fetching package metadata .............


NoPackagesFoundError: Package missing in current linux-64 channels: 
  - bioconda:hmmer
```

What is a possible reason for that?

**Comment by cryptogenomicon** [comment]
Sorry, you'll have to check with whoever packages HMMER for bioconda - that's not us.
