### ISSUE TITLE
Possible to Compile to Windows exe File

### ISSUE THREAD

**Issue by acherrera** [EddyRivasLab/hmmer#186]
Hello, I been asked to fix a workflow that relies on HMMER on a Windows system. The workflow currently has a hmmer3.exe file, but it appears to be an older version than the current 3.3. I would like to compile hmmer for V3.3, but I do not see anyway to do this. Normally I would just move on, but this has clearly been done in the past so I am hoping that it is still possible.

What I've tried - I have successfully downloaded and compiled V3.3 on my Ubuntu machine and validated the workflow. I have read through the hmmer documentation and the only comment about Windows is that it is not supported and can be run on WSL, which is not an open as the workflow needs to be linked to the exe file.

**Comment by npcarter** [comment]
Hello.  We don't support HMMER on Windows, so can't be much help here.  HMMER is written for a UNIX file system, so is very likely not to work correctly on Windows.  It's my understanding that people have had some success building HMMER on Windows using the Cygwin UNIX compatibility libraries, so you might try that, but I haven't tried that myself.

**Comment by acherrera** [comment]
This is my understanding as well - I will look into Cygwin. Has HMMER ever been supported on Windows? I have a copy of an exe HMMER file and I know the person who wants to use it did not compile it.

**Comment by cryptogenomicon** [comment]
We've never been able to support HMMER on Windows, but there's been a few times when people have contributed compiled executables for Windows to us, and we've posted them.

**Comment by acherrera** [comment]
Thank you for the information. I'll consider this closed and see what I can do.
