### ISSUE TITLE
Adding sequences to Pfam alignment

### ISSUE THREAD

**Issue by Neato-Nick** [EddyRivasLab/hmmer#187]
Hi,

I would like iterate my homology searches by searching for a Pfam profile in a protein database, then add the significant results to the hmm-profile (using the Pfam profile to seed the alignment) and re-search.
The hmmer-3.3 release notes say "Profile HMMs built with version 3.3 give slightly different scores compared to previous HMMER3 versions." Unless the Pfam hmms were re-calculated using the v3.3 methods, I'd be worried about the above strategy leading to inconsistent scoring. Would I be best off using the Pfam proteins and generating my own alignment with hmmalign first?

**Comment by cryptogenomicon** [comment]
What you want to do will work fine. Adding new sequences to a profile will change the scores anyway.

The note is only there for people who might notice (in regression tests, perhaps) when HMMER scores aren't absolutely identical between versions. It's not an inconsistency issue, just continuous small improvements in the way we parameterize models.
