### ISSUE TITLE
Converting hmmer bit-scores into posterior for domain hit

### ISSUE THREAD

**Issue by captaincapsaicin** [EddyRivasLab/hmmer#188]
Hello,

I am working on approximating the output of hmmer (the pfam hmms, specifically) with a neural network classifier. In order to train such a classifier, I would want to train it to output for a family F and a query sequence s, p(F|s), i.e. the probability that there is a hit from family F in the sequence s. For simplicity, I'll just assume we are considering only the top-1 domain hit.

The bit-score produced by hmmer, as far as I understand, is:

$$S = \log\dfrac{p(s|F)}{p(s|null_1)} - b$$
![image](https://user-images.githubusercontent.com/10425351/80924703-4d721680-8d3f-11ea-86fb-f2c6d3d4354b.png)

where b is the bias correction term, and p(s|null_1) is the forward probability output by the background, one-state hmm (trained on residue frequencies from Swissprot 50.8). In order to convert that to a family-hit probability P(F|s), I would need to perform the following conversion

$$S' = S + \log\dfrac{p(F)}{p(null_1)}$$

$$p(F|s) = \sigma(S')$$

![image](https://user-images.githubusercontent.com/10425351/80924704-5367f780-8d3f-11ea-9418-26bcc809b441.png)

where \sigma(x) is the logistic function. 

Is there a way to do this conversion (i.e. compute S') from the statistics in the output file of hmmer? If not, what is the appropriate way of going about finding the priors p(F) and p(null_1)? 

Thank you for your help,
Neil

**Comment by cryptogenomicon** [comment]
Yes, that's the correct way to estimate P(F | s). The priors P(F) and P(null) are unknown. A reasonable guess for P(F) is the expected fraction of sequences in the database (Uniprot or whatever) that are homologs in family F, and P(null) = 1 - P(F). Thus P(F) might be something on order of 1/N to 0.01, for a database of N sequences; the smallest families might be single sequences, and the largest protein families, empirically, account for about 1% of known sequences.

**Comment by captaincapsaicin** [comment]
Thank you!
