### ISSUE TITLE
Nhmmer runs without error on protein target database

### ISSUE THREAD

**Issue by npcarter** [EddyRivasLab/hmmer#196]
I accidentally ran nhmmer today on a protein target database file, and it runs without giving any sort of error message.  Not sure what it's doing under the hood, but it takes a while so it's doing some sort of computation.  Is this correct?

Example:
npcarter@elephant-safe-tower:~/hmmer/h3$ src/nhmmer --qformat=genbank ~/Nick/betacoronavirus_genome.gb /data/sequence_dbs/uniprot_sprot.fasta
# nhmmer :: search a DNA model, alignment, or sequence against a DNA database
# HMMER 3.3 (Nov 2019); http://hmmer.org/
# Copyright (C) 2019 Howard Hughes Medical Institute.
# Freely distributed under the BSD open source license.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# query file:                      /home/npcarter/Nick/betacoronavirus_genome.gb
# target sequence database:        /data/sequence_dbs/uniprot_sprot.fasta
# query format asserted:           genbank
# number of worker threads:        2
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Query:       NC_045512  [M=29903]
Scores for complete hits:
    E-value  score  bias  Sequence  start    end  Description
    ------- ------ -----  --------  -----  -----  -----------

   [No hits detected that satisfy reporting thresholds]

Annotation for each hit  (and alignments):

   [No targets detected that satisfy reporting thresholds]

Internal pipeline statistics summary:
-------------------------------------
Query model(s):                            1  (29903 nodes)
Target sequences:                     556825  (399304508 residues searched)
Residues passing SSV filter:          224913  (0.000563); expected (0.02)
Residues passing bias filter:         224123  (0.000561); expected (0.02)
Residues passing Vit filter:           72531  (0.000182); expected (0.003)
Residues passing Fwd filter:            2029  (5.08e-06); expected (3e-05)
Total number of hits:                      0  (0)
# CPU time: 676.31u 0.36s 00:11:16.67 Elapsed: 00:05:36.43
# Mc/sec: 35491.38
//
[ok]

**Comment by traviswheeler** [comment]
This was resolved by PR https://github.com/EddyRivasLab/hmmer/pull/194
