### ISSUE TITLE
Iterative search with a MSA (or "resuming" jackhmmer)

### ISSUE THREAD

**Issue by smsaladi** [EddyRivasLab/hmmer#197]
What's the correct/preferred way to initiate an iterative search with jackhmmer starting with a profile? Alternatively, this would be like initiating jackhmmer with the `-A` aligned hits output of a previous run.

The hmmer manual [suggests ](http://eddylab.org/software/hmmer/Userguide.pdf?#page=123) jackhmmer can accept a multiple sequence alignment as input. However, after much effort, jackhmmer always interprets the input as separate (unaligned) queries against a single target database, even when I specify `--qformat`, e.g.

```text
test% jackhmmer --qformat afa 20aa-alitest.afa rndseq400-10.fa | grep Query
Query:       test1  [L=20]
Query model(s):                              1  (20 nodes)
Query:       test2  [L=25]
Query model(s):                              1  (25 nodes)
Query:       test3  [L=28]
Query model(s):                              1  (28 nodes)
Query:       test4  [L=26]
Query model(s):                              1  (26 nodes)
```

same as the unaligned query:

```text
test% jackhmmer 20aa-alitest.fa rndseq400-10.fa | grep Query   Query:       test1  [L=20]
Query model(s):                              1  (20 nodes)
Query:       test2  [L=25]
Query model(s):                              1  (25 nodes)
Query:       test3  [L=28]
Query model(s):                              1  (28 nodes)
Query:       test4  [L=26]
Query model(s):                              1  (26 nodes)
```

**Comment by cryptogenomicon** [comment]
You can't initiate a `jackhmmer` search from a profile (or MSA), sorry. Both `phmmer` and `jackhmmer` only use single sequence queries.

Both programs can take an alignment file as their input `<seqfile>` query file, but they read it one query sequence at a time, not as an alignment; for an alignment file of _N_ sequences, it'll do _N_ searches. It's the same behavior as when you give them multiple query sequences in an input FASTA file.

I've just made some edits in the man pages to clarify this, and those changes will appear in the next release.

**Comment by smsaladi** [comment]
thanks for clarifying! Now, this also helps make sense of the alignment/profile names and sometimes differing number of alignments at later iterations as well.
