### ISSUE TITLE
hmmbuild no TC in hmm file

### ISSUE THREAD

**Issue by tiramisutes** [EddyRivasLab/hmmer#202]
Hi,
I download the protein sequence alignment in Stockholm format.
![](https://raw.githubusercontent.com/tiramisutes/SynNet-Pipeline/master/seed.png)
and then want to make a model use hmmbuild ( HMMER 3.3) as follows command:
```
hmmbuild PF00931.hmm PF00931_seed.txt
```
But there is miss of TC/GA/MC in PF00931.hmm file.
Any help is much appreciated.
Thanks.

**Comment by cryptogenomicon** [comment]
Yes, the layout of the download options is a little confusing, I guess. The "Format an alignment" section that you're using is for _reformatting_ the Pfam alignment into different formats that you might need for other software. For the original Pfam seed alignment with all its annotation (including the TC/GA/NC cutoffs), use the "Download" option section just below. Click on the check mark at "raw stockholm" / "Seed" and you'll download the Pfam seed alignment.

Hope this helps!

**Comment by tiramisutes** [comment]
Thank you for correcting my mistake. Now, I get the results.
