### ISSUE TITLE
Alignment details in the tabular output

### ISSUE THREAD

**Issue by gy-chop** [EddyRivasLab/hmmer#207]
Hello,

Thanks for developing and maintain the great tool. I just have a quick question. Is there a way to include alignment details in the tabular output of nhmmer (with --tblout or any other parameter) that is easy to parse, just like the BTOP string in BLAST+?

Thanks for your time!

**Comment by cryptogenomicon** [comment]
No, not yet, sorry.

**Comment by nawrockie** [comment]
The --notextw option makes the standard output alignments easier to parse.
