### ISSUE TITLE
configure hmmer3-arm on arm-platform

### ISSUE THREAD

**Issue by X-WJ** [EddyRivasLab/hmmer#214]
Thank you very much for your work on the arm platform. When I downloaded the H3-arm branch and compiled it on my computer, an error occurred. The details are as follows:

./configure  --prefix=`pwd`
configure: Configuring HMMER3 for your system.
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking whether to compile using MPI... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gcc option to accept ISO C99... -std=gnu99
checking for gcc -std=gnu99 option to accept ISO Standard C... (cached) -std=gnu99
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for a BSD-compatible install... /usr/bin/install -c
checking for strip... strip
checking for ranlib... ranlib
checking for ar... /usr/bin/ar
checking whether ln -s works... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking whether gcc -std=gnu99 is Clang... no
checking whether pthreads work with -pthread... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking whether more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking whether gcc -std=gnu99 can compile our Altivec/VMX code... no
checking whether gcc -std=gnu99 can compile our SSE code... no
configure: ::::::::::--- no vector instruction set ---::::::::::
configure: HMMER3 requires SSE, NEON or VMX vector instructions.
configure: Supported platforms are x86 (Intel/AMD), ARM,  and PowerPC.
configure: error: No supported vectorization found for your machine.

My cpuinfo like this
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    1
Core(s) per socket:    16
Socket(s):             2
NUMA node(s):          2
Model:                 0
CPU max MHz:           2400.0000
CPU min MHz:           2400.0000
BogoMIPS:              200.00
L1d cache:             64K
L1i cache:             64K
L2 cache:              512K
L3 cache:              32768K
NUMA node0 CPU(s):     0-15
NUMA node1 CPU(s):     16-31
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm

my cpu is Huawei 920 kunpeng

Can you give  me  some  advices？

**Comment by npcarter** [comment]
Hello,

The ARM version of HMMER is still under development and does not work at
the moment.  We hope to release HMMER for ARM in early 2021.

-Nick
