### ISSUE TITLE
Incomplete install?

### ISSUE THREAD

**Issue by sjaenick** [EddyRivasLab/hmmer#218]
Hi,

I just noticed some of the compiled binaries (such as hmmc2 or hmmerfm-exactmatch) don't
get installed during 'make install' (observed for hmmer-3.3.2 release). Is this on purpose?

Regards,
  Sebastian

**Comment by sjaenick** [comment]
closing, invalid.

**Comment by cryptogenomicon** [comment]
Yes, that's on purpose.
