### ISSUE TITLE
Format tag is '>seq2': unrecognized, file format problem in trying to open HMM file 

### ISSUE THREAD

**Issue by iab-bioinformatics** [EddyRivasLab/hmmer#221]
I created a multi-fasta file via command:

` cat myfasta1.fa myfasta2.fa > mymultifasta.fa`

then I tried to run hmmalign via the following command and I got the error:
```
hmmalign mymultifasta.fa hmm_alignment.hmm

Error: File format problem in trying to open HMM file  mymultifasta.fa.
Format tag is '>seq2': unrecognized.
Current H3 format is 'HMMER3/f'. Previous H2/H3 formats also supported.
```

I think the header is for a normal fasta and I cant understand where is the problem.

**Comment by cryptogenomicon** [comment]
From  the short help for `hmmalign -h`:

```
Usage: hmmalign [-options] <hmmfile> <seqfile>
```
