### ISSUE TITLE
What are the CLUSTAL header requirements?

### ISSUE THREAD

**Issue by RyanPendavingh** [EddyRivasLab/hmmer#226]
Hi,

I used MAFTT (v7.309) to generate a msa in CLUSTAL format. However, HMMer, raises an error on a missing header even though there is one: 
CLUSTAL format alignment by MAFFT FFT-NS-i (v7.309)

What are the exact requirements for the header? Then I can change the header and/or inform Kazutaka Katoh from MAFFT about it.

Thank you

**Comment by cryptogenomicon** [comment]
We look for "multiple sequence alignment" in the header, as in Clustal and MUSCLE output:

```
CLUSTAL W (1.83) multiple sequence alignment
MUSCLE (3.7) multiple sequence alignment
```

I didn't realize MAFFT was formatting its headers differently. I've checked in a change so we'll only check for "alignment". This change will appear in our next release. In the meantime, you can work around the problem by changing your header to something like "CLUSTAL format multiple sequence alignment".
