### ISSUE TITLE
Unable to Configure Hmmer

### ISSUE THREAD

**Issue by Prachikhattar** [EddyRivasLab/hmmer#245]
Error: HMMER3 requires SSE or VMX vector instructions.
Supported platforms are x86 and Power PC.
No supported vectorization found for your machine.

Is there any way I can use Hmmer on my system????

**Comment by npcarter** [comment]
What type of computer are you trying to build HMMER on. Is it an M1 Mac?

[Nick Carter - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=12uz0c)	[12uz0c]

On June 18, 2021 at 3:17 GMT, Prachikhattar ***@***.***> wrote:

Error: HMMER3 requires SSE or VMX vector instructions.
Supported platforms are x86 and Power PC.
No supported vectorization found for your machine.

Is there any way I can use Hmmer on my system????

**Comment by Prachikhattar** [comment]
Yes m1 mac

**Comment by npcarter** [comment]
Ah, yes.  The current version of HMMER does not support the ARM chip in the
M1 Macs.  We have an ARM-compatible version that will be released soon, so
one option for you would be to wait until that is released.  If you don't
want to wait, you can compile HMMER using the Rosetta 2 compatibility tool
that allows ARM macs to run x86 code.  To do that, you'll want to follow
the instructions at
https://osxdaily.com/2020/12/04/how-install-rosetta-2-apple-silicon-mac/ to
install Rosetta 2, and then the instructions at
https://dev.to/courier/tips-and-tricks-to-setup-your-apple-m1-for-development-547g
to create a copy of the terminal app that runs under Rosetta.

Once you've done that, if you open the Rosetta copy of the terminal app and
follow the normal instructions on how to build HMMER it should work.  Note
that you may need to be using the Roseta copy of the terminal app to run
HMMER if you build HMMER using this technique.

-Nick

**Comment by Prachikhattar** [comment]
Okay I shall try that
Thank you so much for your help!
