### ISSUE TITLE
unable to make hmmer for arm platform

### ISSUE THREAD

**Issue by Yvonne-zyf0627** [EddyRivasLab/hmmer#246]
I was getting compiler errors when I tried to compile hmmer-h3-arm on the aarch64 platform:
   % git clone -b h3-arm https://github.com/EddyRivasLab/hmmer.git
   % cd hmmer
   % git clone https://github.com/EddyRivasLab/easel
   % autoconf
   % ./configure
   % make

_Then I got the following error message_:

p7_domain.c: In function ‘p7_domain_Compare’:
p7_domain.c:525:3: error: too many arguments to function ‘esl_FCompare’
   if(esl_FCompare(first->envsc, second->envsc, (float) atol, (float) rtol) != eslOK){
   ^
In file included from p7_domain.c:15:0:
../easel/easel.h:515:13: note: declared here
 extern int  esl_FCompare   (float  a,  float  b, float  tol);
             ^
p7_domain.c:528:2: error: too many arguments to function ‘esl_FCompare’
  if(esl_FCompare(first->domcorrection, second->domcorrection, (float) atol, (float) rtol) != eslOK){
  ^
In file included from p7_domain.c:15:0:
../easel/easel.h:515:13: note: declared here
 extern int  esl_FCompare   (float  a,  float  b, float  tol);
             ^
p7_domain.c:531:2: error: too many arguments to function ‘esl_FCompare’
  if(esl_FCompare(first->dombias, second->dombias, (float) atol, (float) rtol) != eslOK){
  ^
In file included from p7_domain.c:15:0:
../easel/easel.h:515:13: note: declared here
 extern int  esl_FCompare   (float  a,  float  b, float  tol);
             ^
p7_domain.c:534:3: error: too many arguments to function ‘esl_FCompare’
   if(esl_FCompare(first->oasc, second->oasc, (float) atol, (float) rtol) != eslOK){
   ^
In file included from p7_domain.c:15:0:
../easel/easel.h:515:13: note: declared here
 extern int  esl_FCompare   (float  a,  float  b, float  tol);
             ^
p7_domain.c:537:3: error: too many arguments to function ‘esl_FCompare’
   if(esl_FCompare(first->bitscore, second->bitscore, (float) atol, (float) rtol) != eslOK){
   ^
In file included from p7_domain.c:15:0:
../easel/easel.h:515:13: note: declared here
 extern int  esl_FCompare   (float  a,  float  b, float  tol);
             ^
p7_domain.c:540:2: error: too many arguments to function ‘esl_DCompare’
  if(esl_DCompare(first->lnP, second->lnP, atol, rtol) != eslOK){
  ^
In file included from p7_domain.c:15:0:
../easel/easel.h:514:13: note: declared here
 extern int  esl_DCompare   (double a,  double b, double tol);
             ^
p7_domain.c:566:5: error: too many arguments to function ‘esl_FCompare’
     if(esl_FCompare(first->scores_per_pos[i], second->scores_per_pos[i], (float) atol, (float) rtol) != eslOK){
     ^
In file included from p7_domain.c:15:0:
../easel/easel.h:515:13: note: declared here
 extern int  esl_FCompare   (float  a,  float  b, float  tol);
             ^
make[1]: *** [p7_domain.o] Error 1
make: *** [all] Error 2

**Comment by npcarter** [comment]
Hello.  The h3-arm branch of HMMER requires the develop branch of Easel.
From the errors you’re seeing, it looks like you’re compiling against the
master branch of Easel.  If you checkout the develop branch of Easel,
everything should build.

As a note, we generally don’t recommend that people build the non-main
branches of our code, as these are used for development and are often in a
non-functional state.  However, h3-arm is currently in a good state and
will soon be rolled up into a formal release.

**Comment by Yvonne-zyf0627** [comment]
> Hello. The h3-arm branch of HMMER requires the develop branch of Easel. From the errors you’re seeing, it looks like you’re compiling against the master branch of Easel. If you checkout the develop branch of Easel, everything should build. As a note, we generally don’t recommend that people build the non-main branches of our code, as these are used for development and are often in a non-functional state. However, h3-arm is currently in a good state and will soon be rolled up into a formal release.

Thanks very much，I will try again.
