### ISSUE TITLE
How to merge profiles in different format?

### ISSUE THREAD

**Issue by xiekunwhy** [EddyRivasLab/hmmer#250]
Hi,

How to merge following two type of hmm profiles (hmmsearch does not work if I cat them directly):

## type 1
HMMER3/f [3.3.2 | Nov 2020]
NAME  1-cysPrx_C
ACC   PF10417.11
DESC  C-terminal domain of 1-Cys peroxiredoxin
LENG  40
ALPH  amino
RF    no
MM    no
CONS  yes
CS    yes
MAP   yes
DATE  Wed Feb 24 18:37:46 2021
NSEQ  40
EFFN  17.426758
CKSUM 4086680297
GA    21.10 21.10
TC    21.10 21.10
NC    21.00 21.00
STATS LOCAL MSV       -7.5463  0.71948
STATS LOCAL VITERBI   -7.8624  0.71948
STATS LOCAL FORWARD   -4.3303  0.71948

## type 2
HMMER3/f [3.2.1 | June 2018]
NAME  K00001
LENG  400
ALPH  amino
RF    no
MM    no
CONS  yes
CS    no
MAP   yes
DATE  Mon Jul  5 14:37:13 2021
NSEQ  1325
EFFN  13.285685
CKSUM 3713403561
STATS LOCAL MSV      -11.0499  0.69925
STATS LOCAL VITERBI  -13.2873  0.69925
STATS LOCAL FORWARD   -5.0859  0.69925

Best,
Kun

**Comment by cryptogenomicon** [comment]
Shouldn't be any problem with concatenating those two profile files. They are in the same format, `3/f`. Can you provide example files that reproduce the problem?

You can use `hmmconvert` to change the format of profile files. The default is to upgrade an old file to current format, if possible.
