### ISSUE TITLE
Muscle alignment tool

### ISSUE THREAD

**Issue by Prachikhattar** [EddyRivasLab/hmmer#251]
How can I use offline version of muscle alignment tool on Mac m1

**Comment by npcarter** [comment]
Hello,

Muscle is not a tool that our group develops/maintains, so I can't offer
you a definite answer.  That said, I've found Apple's Rosetta 2 tool to be
very effective at running x86 programs on the Mac M1, so you might try that
on an x86 version of Muscle.

-Nick
