### ISSUE TITLE
autoconf failure -- autoconf 2.71

### ISSUE THREAD

**Issue by traviswheeler** [EddyRivasLab/hmmer#255]
While placing HMMER on a new machine (from github source), I've run into an error with running autoconf v 2.71:

% autoconf -V
autoconf (GNU Autoconf) 2.71
Copyright (C) 2021 Free Software Foundation, Inc.
...

% git clone https://github.com/EddyRivasLab/hmmer hmmer
% cd hmmer
% git checkout develop
% git clone https://github.com/EddyRivasLab/easel
% cd easel
% git checkout develop
% cd ..
% autoconf
configure.ac:245: warning: The macro `AC_PROG_CC_STDC' is obsolete.
configure.ac:245: You should run autoupdate.
./lib/autoconf/c.m4:1666: AC_PROG_CC_STDC is expanded from...
configure.ac:245: the top level
configure.ac:281: warning: $as_echo is obsolete; use AS_ECHO(["message"]) instead
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
easel/m4/ax_pthread.m4:88: AX_PTHREAD is expanded from...
configure.ac:281: the top level

Running autoupdate leads to a somewhat more verbose failure, but a failure all the same. This reproduces on both Intel Xeon and AMD Ryzen.  autoconf 2.69 works without error.

Please let me know if you need me to provide any additional information

**Comment by cryptogenomicon** [comment]
Thanks, fixed!
