### ISSUE TITLE
Clarification about e-values from hmmscan

### ISSUE THREAD

**Issue by nattzy94** [EddyRivasLab/hmmer#265]
Hi, 

I queried a fasta file of protein sequences against the pfam database using hmmscan web application. I am a little confused about the difference between `individual e-value` vs. the `full sequence e-value`. 

From the documents, it says that the `independent e-value` (I assume this means `individual e-value)` measures the `significance of the sequence in the whole database search`. It goes on to say that "`If this E-value is not good, but the full sequence E-value is good, this is a potential red flag.`"

I am confused as it seems that the individual e-value already measures the significance of the sequence. Why is there another e-value for the full sequence? Is it perhaps referring to the sub-sequence that aligned to the model?

Also, is it possible to obtain the full sequence e-value using the web interface? I do not see it in the output of either in the batch or individual searches.

Thank you!

**Comment by cryptogenomicon** [comment]
(We think this is already explained in the User's Guide and other documentation.)
