### ISSUE TITLE
[QUESTION] What is the meaning of 'profile' in 'profile-HMM'?

### ISSUE THREAD

**Issue by a-a-k** [EddyRivasLab/hmmer#266]
I'm sorry for such a weird question, but I have got stuck on this as a foreigner. The meaning of this word is too broad for me to translate it in that context and seems there is not any academic translation for this term in my native literature (Russian). Could anyone explain, please?

**Comment by cryptogenomicon** [comment]
If you mean, what's a profile HMM as opposed to an HMM: the states of a standard HMM are allowed to be fully interconnected, with MxM transition probabilities for M states. A profile HMM is specialized for modeling the statistical consensus of a multiple sequence alignment (MSA). It's basically just a line of states, one for each consensus column in the alignment, plus additional states for deletions and insertions; there are only O(M) transitions in a profile HMM.

If you mean, what's the connection to the English word "profile": "profile" means an outline, a sketch, a summary. (My college Russian is almost all gone now, but I think профиль has about the same meaning.) A "profile" of an MSA is a compact statistical model of the consensus conservation pattern of an MSA, summarizing the MSA in a small set of probabilities or scores. When people first started making consensus models of MSAs, "profile" is one of the names that they used that stuck. When people then applied HMM methods to make profiles based on probabilities, they became "profile HMMs".

**Comment by a-a-k** [comment]
Thank you, professor! That's an honor to me to get the answer directly from you and I am surprised you were learning Russian.
