### ISSUE TITLE
hmmfetch: conflicting documentation

### ISSUE THREAD

**Issue by nick-youngblut** [EddyRivasLab/hmmer#270]
The hmmfetch docs state:

```
  -O     Output  HMM(s)  to  individual file(s) named <key> instead of standard output. With
              the -f option, this can result in many files being created.
```

Specifically:

> With the -f option

indicates that `-f` can be used with `-O`, but when used together:

```
$ hmmfetch -O -f Pfam-A.hmm domain_keys.txt
Error in configuration: Option -O is incompatible with option(s) -o,-f,--index
Usage: hmmfetch [options] <hmmfile> <key>         (retrieves HMM named <key>)
Usage: hmmfetch [options] -f <hmmfile> <keyfile>  (retrieves all HMMs in <keyfile>)
Usage: hmmfetch [options] --index <hmmfile>       (indexes <hmmfile>)

To see more help on available options, do hmmfetch -h
```

...so it appears that `-O` cannot actually be used with `-f`. Either the error message is incorrect or the script docs are incorrect. It seems like `-O` should be compatible with `-f`, since I don't see the use of `-O` outside of usage with `-f`.

I'm using `hmmer 3.3.2 bioconda`

**Comment by cryptogenomicon** [comment]
That documentation error was fixed back in Sept 2019 and is not actually present in the 3.3.2 HMMER release. 

(-O is not compatible with -f, currently; the error message is correct and the man page was wrong.)
