### ISSUE TITLE
What does hmmalign do when number of domains > 1?

### ISSUE THREAD

**Issue by reubwn** [EddyRivasLab/hmmer#275]
Hello,

For `hmmalign`, The HMMER docs say (p. 77):
> The sequences in seqfile are aligned in unihit local alignment mode. Therefore they should already be known to contain only a single domain (or a fragment of one).

What is the default behaviour when the sequences in seqfile contain **more than one** of the domain specified in the hmmfile? For example, if I wish to construct an alignment of a protein family that is known to have a bunch of the same domain in a single protein. When I ask `hmmalign` to output in clustal/phylip (for subsequent tree building), is the entry a kind of consensus for all the assigned states at each position in the HMM, spread across the multiple hits it found, or is it simply the top/first hit?

Thanks for your time and for constructing such an excellent piece of software.

**Comment by cryptogenomicon** [comment]
It will align only one best-scoring domain to the profile's consensus; the remainder of the input sequence will be left as unaligned flanking sequence in the output MSA.

**Comment by reubwn** [comment]
Great, thanks for the info.
