### ISSUE TITLE
Build failure on Linux ARM64

### ISSUE THREAD

**Issue by martin-g** [EddyRivasLab/hmmer#276]
Hello,

I've just tried to build `h3-arm` branch (against easel's `develop` branch) on openEuler OS 20.03 ARM64:

```
$ gcc --version
gcc (GCC) 7.3.0
...
$ autoconf
$ ./configure
...

HMMER configuration:
   compiler:             gcc -g -O2 -O3    -mlittle-endian -pthread 
   host:                 aarch64-unknown-linux-gnu
   linker:               
   libraries:              -lpthread
   DP implementation:    neon

$ make
...
$ make check
...
exercise    6 [      generic_viterbi] ...     FAILED [command failed]
...
1 of 307 exercises at level <= 2 FAILED.


System information:
ср апр 20 13:06:21 UTC 2022
Linux mgrigorov-arm64 4.19.90-2203.5.0.0143.oe1.aarch64 #1 SMP Wed Mar 30 17:26:54 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
make[1]: *** [Makefile:41: check] Error 1
make: *** [Makefile:118: check] Error 2

```

Please let me know if you need any specifics about my system and any test output files!

**Comment by npcarter** [comment]
Hello,

Could you run the command src/generic_viterbi_utest --vv in your hmmer
directory and send us the results, please?  I'm at a bit of a loss as to
what could be going on here, as the generic_viterbi module doesn't contain
any ARM-specific code, but hopefully running the utest with verbose turned
on will tell us something useful.

-Nick

**Comment by martin-g** [comment]
```
mgrigorov@mgrigorov-arm64 ~/g/h/h/hmmer (h3-arm)> ./src/generic_viterbi_utest --vv
trace score and Viterbi score don't agree.
```

**Comment by npcarter** [comment]
Just a progress update: tested this benchmark on our M1 Mac, and couldn't
reproduce the problem.  I'm looking for access to an ARM Unix machine to
test on.

-Nick

**Comment by martin-g** [comment]
Hi Nick,

Thanks for looking into this issue!

I can provide you with a Linux ARM64 VM!
Please contact me at martin.grigorov at Gmail com and send me your
preferred spec (flavor, CPU, RAM, disk space,...)

**Comment by martin-g** [comment]
Hi,

I've started from scratch (clone, autoconf, ...) and today I am not able to reproduce the issue with the failing test!
I executed `make check` many times and all tests passed successfully always.

Closing...
I'll let you know if I face any issues!
