### ISSUE TITLE
Unable to run create-profmark.c

### ISSUE THREAD

**Issue by wolf-Peng** [EddyRivasLab/hmmer#281]
Hi,

I am trying to use create-promark.c to create a new training-test set of dna.
I excuted  `./create-profmark pmark sequence.stockholm sequence.fa` where sequence.stockholm was generated by mafft from sequence.fa.
And it raise an error: `Failed to open SSI index file`

Could you help me solve it?
Thank you

**Comment by cryptogenomicon** [comment]
Both the MSA and sequence file need to be indexed for fast sequence lookup and retrieval; we call these index files "SSI" files. The program to create them are `esl-afetch` and `esl-sfetch` in the Easel tools that come with HMMER in the `easel` subdirectory of its source code.

```
    % esl-afetch --index <msafile>
    % esl-sfetch --index <fastafile>
```

**Comment by npcarter** [comment]
Also, we plan to make this error message more informative in the next
release, as a number of people have had the same issue that you did.
-Nick

**Comment by wolf-Peng** [comment]
hello, I wannt to use the develop version of create_profmark and I run the command:
`git clone https://github.com/EddyRivasLab/hmmer
cd hmmer
git clone https://github.com/EddyRivasLab/easel
git checkout develop
autoconf
./configure
make`
Then it raised an error
`esl_sq.c: In function ‘esl_sq_BlockReallocSequences’:
esl_sq.c:611:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for(int i = 0; i < block->listSize; i++){
   ^
esl_sq.c:611:3: note: use option -std=c99 or -std=gnu99 to compile your code
make[1]: *** [esl_sq.o] Error 1
make: *** [all] Error 2
`
How to change it to C99 mode? Thank you.
