### ISSUE TITLE
make error at develop branch

### ISSUE THREAD

**Issue by wolf-Peng** [EddyRivasLab/hmmer#282]
hello, I want to use the develop version of create_profmark.c and I run the command:
`git clone https://github.com/EddyRivasLab/hmmer`
`cd hmmer`
`git clone https://github.com/EddyRivasLab/easel`
`git checkout develop`
`autoconf`
`./configure`
`make`
Then it raised an error
`esl_iset.c: In function ‘esl_iset_Cobalt’:
esl_iset.c:368:5: error: ‘for’ loop initial declarations are only allowed in C99 mode
     for (int i = n; i < n+nb; i++){
     ^
esl_iset.c:368:5: note: use option -std=c99 or -std=gnu99 to compile your code
esl_iset.c: In function ‘esl_bi_iset_Cobalt’:
esl_iset.c:491:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (int i = 2*n; i < 2*n+nb2; i++){
         ^
esl_iset.c:526:7: error: ‘for’ loop initial declarations are only allowed in C99 mode
       for (int i = 2*n; i < 2*n+nb2; i++){
       ^
esl_iset.c:538:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
         for (int i = n; i < n+nb1; i++){
         ^
make[1]: *** [esl_iset.o] Error 1
make: *** [all] Error 2`
How to solve it ? Thank you.

**Comment by cryptogenomicon** [comment]
We are currently working on the develop branch version of create_profmark. Please be patient while we finish!

**Comment by jrherr** [comment]
Just commenting on here to get a ping if there are any updates to this issue.

I am also reinstalling on a M1 Mac. When I run:

```
git clone https://github.com/EddyRivasLab/hmmer
 cd hmmer
 git clone https://github.com/EddyRivasLab/easel
 git checkout develop
 autoconf
 ./configure
 make
```

I then get the following error during compiling:

```
generic_vtrace.c:78:16: error: implicit declaration of function 'esl_FCompare_old' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
      if      (esl_FCompare_old(XMX(i, p7G_C), XMX(i-1, p7G_C) + gm->xsc[p7P_C][p7P_LOOP], tol) == eslOK)  scur = p7T_C; 
               ^
1 error generated.
make[1]: *** [generic_vtrace.o] Error 1
make: *** [all] Error 2
```
...any help is appreciated! Thanks!

**Comment by npcarter** [comment]
It looks to me like you’ve checked out the develop branch of HMMER, but not
the develop branch of Easel, which the develop branch of HMMER requires.
Could you please try checking out the develop branch of Easel as well, and
let me know if that works?

-Nick

**Comment by cryptogenomicon** [comment]
Yes, our develop branch is currently not compiling, and we know about it.
