### ISSUE TITLE
Is AVX for hmmer3 still in process?

### ISSUE THREAD

**Issue by Gy-Lu** [EddyRivasLab/hmmer#285]
Hi, I pulled the code from the branch `h3-avx`.
When I ran `./configure` at the hmmer dir, an error occurred
```
config.status: error: cannot find input file: `src/impl_avx/Makefile.in'
```
And I found there was no such dir named `impl_avx`, I wonder if the AVX support for hmmer3 is still in process? Or I just miss something?

**Comment by npcarter** [comment]
Yes, the h3-avx branch is still in the early stages of development, and is
completely non-functional at the moment.

-Nick

**Comment by Gy-Lu** [comment]
Got it. Thanks for your reply.
