### ISSUE TITLE
to (ali coord) and to (env coord) larger than qlen in domtableout

### ISSUE THREAD

**Issue by ilyavs** [EddyRivasLab/hmmer#288]
Hello,
I am looking at jackhmmer results of my local analysis and see cases where the to (ali coord) and to (env coord) are larger than qlen . The documentation states:

> to (ali coord): The end of the MEA alignment of this domain with respect to the sequence, numbered 1..L for a sequence of L residues.

> to (env coord): The end of the domain envelope on the sequence, numbered 1..L for a sequence of L residues.

So I am confused. How can the end be larger than the number of residues in the query?
How do I get the coordinates of the domain in the query sequence?
Thanks,
Ilya.

**Comment by cryptogenomicon** [comment]
The query is the profile HMM that's been built from your input sequence, and its coords for each hit are in the two `hmm coord` columns `to` and `from`. You're looking at the coordinates for the target sequence that the profile HMM has been aligned to.

**Comment by ilyavs** [comment]
Oh, now I understand. Thank you very much!
In hmmscan it's the same or the other way around? Seems like in hmmscan the hmm coord columns are for the target profiles, right? In that case the env coord is in the protein query coordinates?

**Comment by cryptogenomicon** [comment]
Yes. The HMM coords are always for the profile HMM, and the ali and env coords are always for the protein sequence. In hmmscan, the query is a protein sequence and the targets are profile HMMs.

**Comment by ilyavs** [comment]
Got it. Thank you.
Just making sure, if I want to calculate target coverage for hmm scan I use the hmm coord and tlen. For jackhmmer I can use env coord and tlen. Is that correct?

**Comment by cryptogenomicon** [comment]
Off the top of my head yes, but it's best to check the documentation on this; that's why it's there.

**Comment by ilyavs** [comment]
Of course I checked the documentation before even posting this issue. That's why I asked for clarification.
Thanks for confirming.
