### ISSUE TITLE
Error: No MAXL field in model(s)

### ISSUE THREAD

**Issue by TangShan99** [EddyRivasLab/hmmer#291]
Hi,
I have a confusing but possibly trivial issue，the following prompt appears when I try to run nhmmscan：

`Error: No MAXL field in model(s); is this an old model format? nhmmer/hmmscan require HMMER 3.1 models or later.`

However, my HMMER version is already the latest (HMMER 3.3.2 ), I wonder why does this issue occur when using nhmmscan? Thanks for your help.

Best,
Kiarety

**Comment by traviswheeler** [comment]
I could use a bit more information.
(1) Did you build the model(s) yourself, using hmmbuild? If not, where did you get them?
(2) Are the models for nucleotide families, or protein?
(3) Can you please provide the results of the following command (replacing filename.hmm with the name of your file):
`head filename.hmm`

**Comment by TangShan99** [comment]
Hi,
Thank you for your quick reply ！
Actually, I didn't use `hmmbuild`, I just use my own sequences searching against HMMs database, which I download is Pfam-A.hmm from this web site ( http://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz ), and the model could be available for protein. As you suggested，when I run the appointed command there comes the result：
`
HMMER3/f [3.1b2 | February 2015]
NAME  1-cysPrx_C
ACC   PF10417.12
DESC  C-terminal domain of 1-Cys peroxiredoxin
LENG  40
ALPH  amino
RF    no
MM    no
CONS  yes
CS    yes

`
It seems that the old version of HMMER3 associated with Pfam-A.hmm is going wrong,  so I was wondering if I would take `hmmscan` instead of `nhmmscan` to continue running, although more time it would take. Any other solution can help me? Thanks a lot.

Best,
Kiarety

**Comment by traviswheeler** [comment]
That makes sense. 
- nhmmer and nhmmscan are intended to perform nucleotide-to-nucleotide search
- Pfam is a database of protein domains (you can see this in the line "ALPH amino")
- This means than nhmmscan will fail when using Pfam as a database. The error message isn't particularly helpful in explaining this...
- I'm not sure if your query sequences are proteins or nucleotides.
     - If protein, then you should be able to use hmmscan
     - If nucleotide, then you'll need to somehow account for the fact that this is "translated search". One common way is to find all ORFs in the nucleotide sequences (e.g. using the tool esl-translate that comes with HMMER), then search those

**Comment by TangShan99** [comment]
Thanks, I have finally solved it by using `hmmscan`. Thank you to tell me so much helpful suggestions.
