### ISSUE TITLE
Hmmbuild segmentation failure

### ISSUE THREAD

**Issue by spiceeeheu** [EddyRivasLab/hmmer#293]
Hi, I am trying to build a profile with my sequence files and I face input failure. 
Alignment input open failed.
/cm/local/apps/slurm/var/spool/job112730/slurm_script: line 14: 29906 Segmentation fault      hmmbuild 350_fq1.hmm /storage/homes/jiatongh/anvio/350_fq1.fq

I am not really sure what is wrong (or my input file format was wrong), I ran it on a linux ssh and the assigned memory is 1gb. My fq is forward sequence that is roughly 10 gb. I would really appreciate any help! Thanks

**Comment by cryptogenomicon** [comment]
I'm not sure what you're trying to do here, but you might want to start with the tutorial in the User's Guide to learn more about how HMMER works and what it's for.

I'm guessing that your input .fq file is a 10G FASTQ file of reads, but HMMER `hmmbuild` is expecting to get a multiple sequence alignment of a particular sequence family that you want to make a profile HMM of, not a FASTQ read file.
