### ISSUE TITLE
standard realloc error when running hmmer in QIIME2 

### ISSUE THREAD

**Issue by Krupa-17** [EddyRivasLab/hmmer#295]
Hello!

I was wondering if someone could help me with an issue I have been having running hmmer in  QIIME2 for PICRUST - I am running into a realloc error (command and error shown below) Previously, the error was that there was not enough space in my tmp directory which is why I changed it to another location which have over 5TB of space and checked that the command is directing to the new tmp location using echo.

The command:
qiime picrust2 full-pipeline
--i-table tmp_to_delete/feature-table.qza
--i-seq tmp_to_delete/sequences.qza
--output-dir q2-picrust2_output_wgs
--p-placement-tool sepp
--p-threads 1
--p-hsp-method mp
--p-edge-exponent 0
--p-max-nsti 2
--verbose

The error:

Error running this command:

place_seqs.py --study_fasta /SAN/tmp/tmp29_2eqcm/seqs.fna --ref_dir /SAN/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref --out_tree /SAN/tmp/tmp29_2eqcm/picrust2_out/out.tre --processes 1 --intermediate /SAN/tmp/tmp29_2eqcm/picrust2_out/intermediate/place_seqs --min_align 0.8 --chunk_size 5000 --placement_tool sepp

Standard error of the above failed command:

Error running this command:

hmmalign --trim --dna --mapali /SAN/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.fna --informat FASTA -o /SAN/tmp/tmp29_2eqcm/picrust2_out/intermediate/place_seqs/query_align.stockholm /SAN/miniconda3/envs/qiime2-2021.4/lib/python3.8/site-packages/picrust2/default_files/prokaryotic/pro_ref/pro_ref.hmm /SAN/tmp/tmp29_2eqcm/seqs.fna

Standard error of the above failed command:
Fatal exception (source file p7_omx.c, line 159):
realloc for size -1777974705 failed

I am not sure why this is the case - I am running the script with 60G of memory and setting it for 12 hours though it fails in under an hour. Any help would be appreciated!

**Comment by cryptogenomicon** [comment]
It's running out of memory; the alignment you're trying to create must be very large. hmmalign can definitely require >60G on some very large alignments. It would help to have a simpler case, boiled down to just a HMMER command that fails for you, with a minimal number of files and switches, but the main thing is probably going to be the size of the alignment problem. How large is the profile in `pro_ref.hmm` in consensus states, and how many sequences are in `seqs.fna` and of what lengths?
