### ISSUE TITLE
select suitable sequence length

### ISSUE THREAD

**Issue by AlisaGU** [EddyRivasLab/hmmer#297]
Hi, following your advice, I got ORFs instead of the translated genome via breaking the translated genome by stop codons.
A lot of ORFs are shorter than 5bp, and it seems that it's too short to predict by hmmer3.
Filtering is a good solution to avoid this problem.
Could you give me some tips about a suitable sequence length threshold to filter?

**Comment by cryptogenomicon** [comment]
That's something you have to decide. It's not really a problem for HMMER if you have short ORFs (even 1 aa); you just won't tend to be able to find significant matches to very short ORFs.
