### ISSUE TITLE
Is it possible to speed up phmmer searches with makehmmerdb ?

### ISSUE THREAD

**Issue by gciaberi** [EddyRivasLab/hmmer#303]
In the documentation about `makehmmerdb`, it says "... is used to create a binary file from a DNA sequence file." Can it be used for protein databases ? I've tried running it with default parameters on Uniref90, but after some time the process stops and I get "Killed" in my terminal.

Are there other ways of speeding up search speed with `phmmer` beyond the `--cpu` option ?

**Comment by cryptogenomicon** [comment]
From the documentation:

```
makehmmerdb is used to create a binary file from a DNA sequence file. This binary file 
may be used as a target database for the DNA search tool nhmmer.
```

No, it doesn't work for `phmmer` or programs other than `nhmmer`.
