### ISSUE TITLE
Can you use Hmmer annotated files to get count table?

### ISSUE THREAD

**Issue by lilyyycao** [EddyRivasLab/hmmer#305]
Hello, I have done a de novo assembly and used prodigal in order to predict protein coding gene regions. I then used hmmer to do annotations based off of the pfamA database and got the resulting output file but was wondering if there was a way to output a file with count data or is that data lost after using hmmer. Thank you.

**Comment by npcarter** [comment]
Hello.  It looks like you forgot to attach the output file.  Also, when you say "count data", what exactly are you trying to count?

**Comment by npcarter** [comment]
I don't believe we have an option that generates exactly what you're looking for, but I'd suggest that you take a look at the --tblout and --domtblout options to hmmsearch, which generate tablular output files that are intended to be easier for other programs to parse.  --tblout generates an output file with one line per sequence-HMM comparison hit, while --domtblout generates a file with one line per domain that was deemed to be a significant match.  My guess is that it'll be fairly easy to write a Python or other script that generates the table you're looking for from one of those output files.

**Comment by lilyyycao** [comment]
Thank you for your help, I will go ahead and take a look at those options!

**Comment by npcarter** [comment]
I don't know of any way to modify what HMMER lists in the description field, sorry.  It doesn't look like it'd be too hard to write a script to extract the full descriptions from the standard output and substitute them it the tblout, though.  You might try that.
