### ISSUE TITLE
hmmscan cannot utilize multiple threads. 

### ISSUE THREAD

**Issue by dianzhiyong** [EddyRivasLab/hmmer#306]
hmmscan cannot utilize multiple threads. 
For example, the following code "hmmscan --tblout maweisong_gene.fa.out -E 1e-5 --noali --cpu 8 ./Pfam-A.hmm gene.fa" cannot invoke multiple CPU cores for execution.
The Operating System is AlmaLinux

Can you give me some advice ,thank you

**Comment by cryptogenomicon** [comment]
Yes, it does. (If you check, you'll see the threads running.) But hmmscan scales very poorly across multiple cores, because it is input-bound on all but very fast storage systems. That failure to scale is probably what you mean. We generally don't try to run hmmscan on more than 2 cores.
