### ISSUE TITLE
testsuite failures when built as library for infernal

### ISSUE THREAD

**Issue by nawrockie** [EddyRivasLab/hmmer#310]
When building infernal, if user makes a build dir that differs from the src dir and configures there before configuring at the top level (in `infernal/`) then the easel subdir of hmmer dir in the build dir does not include the `formats` directory and so two hmmer testsuite.sqc files fail (`j/--mxfile` and `phmmer/--mxfile`).

**Comment by nawrockie** [comment]
I created PR #309 as a proposal to address this.

**Comment by cryptogenomicon** [comment]
Fixed by merging your PR #309. Thanks!
