### ISSUE TITLE
read_asc{2,3}0hmm returning unset status

### ISSUE THREAD

**Issue by nawrockie** [EddyRivasLab/hmmer#311]
There's a few cases in `p7_hmmfile.c::read_asc{2,3}0hmm` where status is returned when it hasn't been set to an error code. I came across these after stumbling upon the same situation in infernal, where the code had been copied from hmmer. An HMM file would have to be invalid in a very specific way for this to ever cause an issue, but still probably worth fixing. I will prepare a PR to address this.

**Comment by cryptogenomicon** [comment]
Fixed by merging your PR #312. Thanks!
