### ISSUE TITLE
Changelog Hmmer 3.4

### ISSUE THREAD

**Issue by davidbio** [EddyRivasLab/hmmer#313]
Thank you for your great work.
I was not able to find a changelog for Hmmer 3.4.

Is it available somewhere?

**Comment by cryptogenomicon** [comment]
The release notes are in the file `RELEASE-3.4.md` in the source code distribution, and also [here in git](https://github.com/EddyRivasLab/hmmer/blob/master/release-notes/RELEASE-3.4.md).

**Comment by davidbio** [comment]
No offense, but putting it in the main README or in the release section would give it more visibility.
