### ISSUE TITLE
hmmscan should just output tsv

### ISSUE THREAD

**Issue by nhartwic** [EddyRivasLab/hmmer#314]
hmmscan output is needlessly annoying to parse. It is whitespace delimited, but some whitespace, particularly whitespace in "description of target" does not act as a delimiter. While proper escaping or quoting could resolve this, a practical sollution would involve just switching to tab as a separator. 

For backwards compatibility, outputting tsv may need to be enabled via a flag.

**Comment by cryptogenomicon** [comment]
Noted.

**Comment by nhartwic** [comment]
To be clear, I'm referring to the output that is already tabular, available from "--tblout" or "--domtblout". Is there any reason why these tables use inconsistent field separators?

**Comment by cryptogenomicon** [comment]
Yes, there is. The reasons have been discussed at length already elsewhere. So has the ease of parsing these files with  pandas, python, perl, awk, or whatever.  I won't have anything else to say about it here, sorry; this is not the place for the discussion.

**Comment by nhartwic** [comment]
Fair enough. See you around.

**Comment by RamRS** [comment]
If you're space-delimiting output and claiming it's parser friendly while neither quoting multi-word column names nor replacing their internal spaces with hyphens or underscores, I find it hard to believe your stance "I still stubbornly feel that space-delimited files are just as easily parsed as tab-delimited files." is well thought-out.

**Comment by cryptogenomicon** [comment]
Noted.
