### ISSUE TITLE
Error messages about illegal command-line options appear to be getting cut off in some cases

### ISSUE THREAD

**Issue by npcarter** [EddyRivasLab/hmmer#317]
### The error message that hmmsearch and at least some other tools returns in response to an illegal set of command-line options appears to get cut off in some cases

Example: 
/home/npcarter/h3-server/src/hmmsearch --incE 10 --incT 3 Caudal_act.hmm tiny.fasta
Failed to parse command line: Option --incE is incompatible with option(s) --incE,--incT,--cut_ga,-

Hmmsearch has correctly detected the incompatible options, but the list of options that are incompatible with --incE should be (at least according to my read of the code): "--incE,--incT,--cut_ga,--cut_nc,--cut_tc".

Reporting this as an issue because I don't want to be distracted fixing it now, but don't want it to get lost.

**Comment by cryptogenomicon** [comment]
Fixed, over in Easel (f47cc603). This was an esl_getopts problem, with its formatting of a fixed-length error message buffer.
