### ISSUE TITLE
Nhmmer: different (2x smaller) e-values with fasta and hmmerdb

### ISSUE THREAD

**Issue by Augustin-Zidek** [EddyRivasLab/hmmer#319]
Nhmmer reports different e-values (consistently off by an exact factor of 2) when I run against a fasta and a hmmerdb made from that fasta using `makehmmerdb`.

**Reproduction**

1. Download rfam, let's call it `rfam.fasta`.
2. Produce HMMERDB from the downloaded fasta: 
   ```
   makehmmerdb rfam.fasta rfam.hmmerdb
   ```

3. Run Nhmmer against the hmmerdb:
   ```sh
   nhmmer --tblout /tmp/tblout.txt --rna --watson -A /tmp/output.a3m /tmp/query.a3m rfam.hmmerdb
   ```

3. Run Nhmmer against the fasta:
   ```sh
   nhmmer --tblout /tmp/tblout.txt --rna --watson -A /tmp/output.a3m /tmp/query.a3m rfam.fasta
   ```

**Expected result**
Since I ran with `--watson`, I would expect the e-values to match, but they are consistently off by a factor of 2, with the hmmerdb being 2x larger.

**More observations**
* There are 12 cases: {watson, crick, both} × {fasta, hmmerdb} × {z-value set, z-value unset}
* If I set the z-value, the e-values are consistent.
* If I don't set `--watson` or `--crick`, the e-values are also consistent.
* I would expect the e-values to not depend on whether I used fasta or hmmerdb.
* I suspect the bug might be around here: https://github.com/EddyRivasLab/hmmer/blob/master/src/nhmmer.c#L1108

**Comment by cryptogenomicon** [comment]
Thanks (and thanks for the concise and excellent summary).  I've fixed that in our develop branch, and the fix will appear in the next release.

**Comment by Augustin-Zidek** [comment]
Thanks for the quick fix!
