### ISSUE TITLE
makehmmerdb segmentation issue

### ISSUE THREAD

**Issue by BioFalcon** [EddyRivasLab/hmmer#328]
Hi, 

I noticed that I get errors from `nhmmer` when using a database made with `makehmmerdb`, however this errors go away if I use the genome as a fasta file, any idea of why this is?

Thanks!

**Comment by cryptogenomicon** [comment]
I don't know. Please give me more information about the problem you're seeing, enough so that I can reproduce it here - including the version of HMMER you're using, and on what kind of machine.

**Comment by BioFalcon** [comment]
Hi, it seems like I messed up the versions, I was using 3.3.2 and when I used 3.4 everything ran smoothly :)

**Comment by cryptogenomicon** [comment]
Great, glad that fixed it. Yes, we fixed some bugs in nhmmer's FM-index searches (the index that `makehmmerdb` makes) in the 3.4 release.
