### ISSUE TITLE
HMMER error

### ISSUE THREAD

**Issue by mesti90** [EddyRivasLab/hmmer#332]
defense-finder 1.3.0 aborted with the following error message in defense-finder-tmp/DF_1/hmmer_results/radar_II__rdrA_II.search_hmm.err:

Fatal exception (source file p7_pipeline.c, line 714):
Target sequence length > 100K, over comparison pipeline limit.
(Did you mean to use nhmmer/nhmmscan?)
Aborted (core dumped)

HMMER version number is 3.4

The file on which it stopped working is attached.

[GCA_022437905.1.fna.gz](https://github.com/user-attachments/files/16784345/GCA_022437905.1.fna.gz)

**Comment by cryptogenomicon** [comment]
Error message seems self-explanatory. hmmsearch has a length limit of 100K residues for target sequences. Your input is a 560kb DNA sequence. If you want to search long DNA sequences, that's what nhmmer does. 

If this is an issue in someone else's pipeline (defense-finder, for example), you may want to report the problem to them. This doesn't appear to be a problem in HMMER.

**Comment by mesti90** [comment]
Sorry, I meant to open this issue in the defense-finder pipeline
