### ISSUE TITLE
Illegal character error

### ISSUE THREAD

**Issue by berkelem** [EddyRivasLab/hmmer#334]
I am encountering the following error with v3.4:

```
Line 278384: illegal character -
```

The following is from the input file:

```
278380	MILSVLSSPALVSGLMVVRAKNPVHSVLFLIPVFRNTSGLLLLLGLDFFAMIFPVVYIGAIAVSFLFVVMMFHIQIAEIH
278381	EEVLRYLPVSGIIGLIFWWEMFFILDNESIPLLPTQRNTTSLRYTVYAGKVRSWTNLETLGNLLYTYYFVWFLVSSLILL
278382	VAMIGAIVLTMHRTTKVKRQDVFRRNALDSRRTIMRRTTDPLTTIRRSSGSNPHREL
278383	>lcl|NC_035963.1_prot_YP_009430469.1_37563 [gene=rps4] [locus_tag=CQW56_mgp14] [db_xref=GeneID:34678310] [protein=ribosomal protein S4] [exception=RNA editing] [protein_id=YP_009430469.1] [location=complement(292085..293134)] [gbkey=CDS]
278384	-RYALPALRFKTCRLLSGNVWNRELTIIQRRILGRLRNKKRSIKRKIYSRENLNSYIQSQTTRKLSLFYGDLPITEMHRG
278385	RERTSYIPFLLNPETRSDVIPVRLHFCETIPQARQPISHRRVCVNNGMVNITHFKLSHGDIISFQENDARTRGEEIKRSF
278386	YIEISVEKIIGKFLDHPWRRTKTEWFRLLKTKRGCRLLLKSRFLQQLRSSMQEEDLERTKKFGSEKVCLGSSFAEHNRMK
278387	RNFYHFKSLFLSKRRNEKNRNIPTRTRSPIVYNSSLYSNSTYCSAPPHQFTKKIKIKRIELPTHYSEVNHRTPKAVVSYG
278388	PNIGHIPHDIRLKDPNLLLRSGKGRGQNI
```

This file works fine with hmmer 3.1b2 but it fails with v3.4. Is there workaround or should I use the older hmmer version?

**Comment by cryptogenomicon** [comment]
What behavior are you expecting? The error message is correct: if that's a FASTA file, there shouldn't be a - character in a sequence.

**Comment by berkelem** [comment]
Yes there may be an issue in the file, but it has worked well with previous HMMER versions, and now it's failing with version 3.4. Is there a way to relax the newer HMMER version's increased restrictiveness with input files?

**Comment by cryptogenomicon** [comment]
No, sorry, there's not. It's behaving correctly. We generally don't want to accept incorrect input formats. That tends to lead to other problems that are worse. The fix is to fix the format of the file.

**Comment by berkelem** [comment]
Ok thanks!
