### ISSUE TITLE
Reason for fixed MAX_BLOCK_SIZE in HMMER3 MPI

### ISSUE THREAD

**Issue by felipegb94** [EddyRivasLab/hmmer#5]
Hi!

I have been using hmmer (mainly hmmsearch) for the past couple months and have been looking at its MPI performance. I was wondering if there was any specific reason for the value given to the MAX_BLOCK_SIZE constant (512x1024 = 0.5 Megabytes). If I am correct, this variable dictates how large a block of the sequence database is given at a time to an MPI worker. Did you arrive to this number empirically? If so, do you still have the results laying around? Would it be a good idea to vary this number depending on the size of the sequence database given and also the number of mpi workers available? 

Also in the Accelerated profile HMM searches paper, you mention that the MPI parallelization scales poorly (2-4 cores), but I have actually seen it scale a bit better than that when given a large enough problem size. Has there been any significant modifications to the MPI parallelization?

When running hmmsearch I usually give it the Pfam-A.hmm database and .fasta files of varying sizes.

Thank you!
Best,
Felipe

**Comment by cryptogenomicon** [comment]
No, there's no specific reason for the MAX_BLOCK_SIZE other than intuition.

We have not done any new work on MPI for a while.
