### ISSUE TITLE
Compiler runs out of registers when using gprof

### ISSUE THREAD

**Issue by stationarysalesman** [EddyRivasLab/hmmer#6]
Since the --enable-gprof option only uses -O, and since so many functions are inlined, compiling fwdfilter.c actually causes the compiler to run out of registers. I fixed this by removing the -O flag in the gprof compiler flag options, which may or may not be what we want. I ran into this problem on the NVIDIA board running all 64-bit (kernel and userspace) software. Since this might affect several branches I've refrained from making a pull request.

**Comment by cryptogenomicon** [comment]
Off the top of my head, I thought that gprof in general would not work properly at high optimization levels (-O3). Have you checked on os/x or linux?
