### ISSUE TITLE
Missing "#=GF ID" with "-A" option on nhmmer (& presumably hmmsearch) searches with multiHMMs. 

### ISSUE THREAD

**Issue by ppgardne** [EddyRivasLab/hmmer#7]
Hi Sean,

Just spotted a minor issue. We've used a multi-hmm to search a bunch of genomes with either nhmmer or hmmsearch. When we use "-A" we get some lovely Stockholm alignments, but it'd be handy to have a  "#=GF ID" line containing the name of which hmm the alignment was generated from (each hmm has a corresponding unique e.g. "NAME  GlmY". e.g. 

 # STOCKHOLM 1.0
 
 #=GF ID GlmY
 #=GS CP007259/3866060-3867261 DE [subseq from] [subseq from] CP007259
 ...
 //

We can map each alignment back to each hmm using "tblout" outputs, but it'd be much easier with ID lines. Then we can esl-afetch goodness too. 

Some minimal illustration+versions below. 

I hope all is well in Boston. I see the US is losing the Olympics. ;-)
http://www.medalspercapita.com/

Cheers,
@ppgardne & @biobeth 

 # nhmmer :: search a DNA model or alignment against a DNA database 
 # HMMER 3.1b2 (February 2015); http://hmmer.org/
 nhmmer -A test.stk --tblout test.tblout  sRNA.hmm test.fa > test.nhmmerout

Produces:
 # STOCKHOLM 1.0
 
 #=GS CP007259/3866060-3867261 DE [subseq from] CP007259
 ...
 CP007259/3866060-3867261         GAAT...
 ...
 //

 # hmmsearch :: search profile(s) against a sequence database
 # HMMER 3.1b2 (February 2015); http://hmmer.org/

 hmmsearch -A test.stk --tblout test.tblout  sRNA.hmm test.fa > test.hmmsearchout

Produces:
 # STOCKHOLM 1.0
 
 #=GS CP007259/3866060-3867261 DE [subseq from] [subseq from] CP007259
 ...
 CP007259/3866060-3867261         GAATGC...
 ...
 //

**Comment by cryptogenomicon** [comment]
Done. hmmsearch, jackhmmer, nhmmer, phmmer and hmmpgmd will now put name, accession, description, and author (i.e. "hmmsearch 3.1b3") into an MSA that's saved with -A. This will appear in the next HMMER3 release Real Soon Now. We appreciate your business and we will punish you for the gratuitous anti-American crack at the appropriate time.
